apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cirros2-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: cirros2-pod
      labels:
        case: label-cirros2      
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: extraRuntime
                operator: In
                values:
                - virtlet
      containers:
        - name: cirros2
          image: virtlet/github.com/eprasad/virt-cirros/raw/master/virt-cirros-0.3.4-x86_64-disk.img
          ports:
          - name: ssh
            containerPort: 22
