apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cirros2-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: cirros2-pod
      labels:
        case: label-cirros2
      annotations:
        kubernetes.io/target-runtime: virtlet
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "extraRuntime",
                        "operator": "In",
                        "values": ["virtlet"]
                      }
                    ]
                  }
                ]
              }
            }
          }
    spec:
      containers:
        - name: cirros2
          image: virtlet/image-service.kube-system/cirros
          ports:
          - name: ssh
            containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: cirros2-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    case: label-cirros2
  ports:
  - name: tcp-22
    protocol: TCP
    port: 22
    targetPort: ssh
