apiVersion: v1
kind: Pod
metadata:
  name: miha-ubuntu-server-pod
  labels:
    case: miha-ubuntu-server-pod
  annotations:
    kubernetes.io/target-runtime: virtlet
    scheduler.alpha.kubernetes.io/affinity: >
      {
        "nodeAffinity": {
          "requiredDuringSchedulingIgnoredDuringExecution": {
            "nodeSelectorTerms": [
              {
                "matchExpressions": [
                  {
                    "key": "extraRuntime",
                    "operator": "In",
                    "values": ["virtlet"]
                  }
                ]
              }
            ]
          }
        }
      }
spec:
  containers:
    - name: miha-ubuntu-server
      image: virtlet/image-service.kube-system/server-ubuntu.qcow2      
      ports:
        - name: web
          containerPort: 80
        - name: ssh
          containerPort: 22
